= *Change Password*

*`PUT` /v2/mobile/password/change*

The endpoint is designed for link:https://github.com/crypterium-com/api-vault/wiki/Password-Change-Process[changing the password] of a user on a mobile device. When a client sends a request to change the password using this method, they should provide the current password and the new password.

== Request

=== Body

Media Type: application/json

==== Parameters

- *currentPassword*: string (required)
The customer's current password.

- *newPassword*: string (required)
The new password that the customer wants to set.

==== Example body

[source,json]
----
{
  "newPassword": "1234Qwerty1234",
  "currentPassword": "1234Qwerty"
}
----

==== Request Sample: cURL

[source,shell]
----
curl --request PUT \
  --url https://crpt-backend-main-service.sandbox.testessential.net/v2/mobile/password/change \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZGQyYzA2YS01ZTAyLTQ3ZjMtYWM5Zi1hYzE4Y2Q5Y2ZiNDQiLCJleHAiOjE3MDk4MDk1MTksImlhdCI6MTcwOTcyMzExOX0.TRES3bszzXjyvQvSqjnt7fUEm52-JQgAr4r7kaxcG84' \
  --header 'Content-Type: application/json' \
  --data '{
  "newPassword": "1234Qwerty1234",
  "currentPassword": "1234Qwert"
}'
----

== Responses

[.collapsible]
====

*`200 - Success response`*

The response status code indicates that the request was successfully processed.

.Media type: application/json

.**result**: string
Indicates the result of the password change operation.

**Responses example**
[source,json]
----
{
  "result": "ok"
}
----
====
[.collapsible]

[.collapsible]
====

*`400 - Bad Request`*

The response status code indicates that the server cannot or will not process the request due to something perceived as a client error.

.Media type: application/json

.*message:* string
Message displayed to the user.

.*field:* string
Specifies the field in the request that caused the error.

.*errorId:* integer
Identifier of the error.

.*systemId:* string
Identifier of the component.

.*originalMessage:* string
The original error message.

.*errorStackTrace:* string
The place where the error occurred in the code.

.*data:* object
Additional data related to the error, strutured as key-value pairs.c

- **additionalProp1:** object
- **additionalProp2:** object
- **additionalProp3:** object

.*error:* string
Identifier of the error.

**Responses example**
[source,json]
----
{
  "error": "COMMON",
  "errorId": 0,
  "message": "Sorry for inconvenience. We're fixing the issue. If you have urgent questions, contact support",
  "systemId": "core"
}
----
====