= *Confirm Email*

*`GET` /v2/mobile/email/confirm*

The endpoint is to confirm an email address.

[IMPORTANT]
====
🚧 The data must be encoded in **base64** format using your frontend
====

== *Request*

=== *Body*


.Media Type: application/json


==== *Query Parameters*

- *email*: string (required)
The email address to be confirmed.

- *event*: string (required)
The event related to the email confirmation.

- *token*: string (required)
The token associated with the email confirmation process. It is sent to the user via email as part of the confirmation process. EMAIL_ADD is encoded in Base64 format.


== Responses

[.collapsible]
====
*`200 - Success response`*


The response status code indicates that the request was successfully processed.

[.collapsible-content]

.**result:** string
indicates the result of the email address confirmation operation.


**Responses example**
[source,json]
----
{
  "result": "ok"
}
----

====

[.collapsible]
====
*`400 - Bad Request`*

The response status code indicates that the requested page was not found on the server.

[.collapsible-content]

.*message:* string
Message displayed to the user.

.*field:* string
Specifies the field in the request that caused the error.

.*errorId:* integer
Identifier of the error.

.*systemId:* string
Identifier of the component.

.*originalMessage:* string
The original error message.

.*errorStackTrace:* string
The place where the error occurred in the code.

.*data:* object
Additional data related to the error, structured as key-value pairs.

** **additionalProp1:** object
** **additionalProp2:** object
** **additionalProp3:** object

.*error:* string
Identifier of the error.

**Responses example**

[source,json]
----
{
  "error": "COMMON",
  "errorId": 0,
  "message": "Sorry for inconvenience. We're fixing the issue. If you have urgent questions, contact support",
  "systemId": "core"
}
----

====
