= *Get Current Customer Profile*

*`GET` /v2/customer/profile*

The endpoint is designed to retrieve the current customer profile. This request returns information about the customer, including their identification details, contact information, consent statuses, Know Your Customer (KYC) level, loyalty level, balance, additional account parameters, and other relevant details.


== Responses

.*`200 - Success Response`*
[%collapsible.200]

====
If a user's field with information is not filled (meaning it has a NULL value), then in the response to a `GET` */v2/customer/profile* endpoint, the value of this field will not be included in the response body.



++++
<h4>Body</h4>
<ul>
  <li><strong>email</strong>: string<br>
    Customer's email address.
  </li>
  <li><strong>confirmedEmail</strong>: boolean<br>
    Confirmation status of the email.<br>
    Default: <code>true</code>
  </li>
  <li><strong>phone</strong>: string<br>
    Customer's phone number.
  </li>
  <li><strong>firstName</strong>: string<br>
    Customer's first name.
  </li>
  <li><strong>lastName</strong>: string<br>
    Customer's last name.
  </li>
  <li><strong>primaryCurrency</strong>: string<br>
    Main currency.
  </li>
  <li><strong>residenceCountry</strong>: string<br>
    Country of residence for the customer.
  </li>
  <li><strong>residenceState</strong>: string<br>
    Customer's residence state.
  </li>
  <li><strong>residenceCity</strong>: string<br>
    Customer's residence city.
  </li>
  <li><strong>residenceStreet</strong>: string<br>
    Customer's residence street.
  </li>
  <li><strong>residenceZipCode</strong>: string<br>
    Customer's residence postal code.
  </li>
  <li><strong>pushEnabled</strong>: boolean<br>
    Whether push notifications are enabled.<br>
    Default: <code>true</code>
  </li>
  <li><strong>enabled2FA</strong>: boolean<br>
    Whether two-factor authentication is enabled.<br>
    Default: <code>true</code>
  </li>
  <li><strong>dateOfBirth</strong>: string&lt;date-time&gt;<br>
    Date of birth for the customer.<br>
    Match pattern: <code>YYYY-MM-DDThh:mm:ss&lt;TZDSuffix&gt;</code>
  </li>
  <li><strong>veroId</strong>: string<br>
    Customer's identifier in the Vero system.
  </li>
</ul>


++++

**Responses example**
[source,json]
----
{
"result": "ok"
}
----
====

.*`400 - Bad Request`*
[%collapsible.400]
====
The response status code indicates that the requested page was not found on the server.

[.collapsible-content]

++++
<h4>Body</h4>
<ul>
  <li><strong>message</strong>: string<br>
    Message displayed to the user.
  </li>
  <li><strong>field</strong>: string<br>
    Specifies the field in the request that caused the error.
  </li>
  <li><strong>errorId</strong>: integer<br>
    Identifier of the error.
  </li>
  <li><strong>systemId</strong>: string<br>
    Identifier of the component.
  </li>
  <li><strong>originalMessage</strong>: string<br>
    The original error message.
  </li>
  <li><strong>errorStackTrace</strong>: string<br>
    The place where the error occurred in the code.
  </li>
  <li><strong>data</strong>: object<br>
    Additional data related to the error, structured as key-value pairs.
    <ul>
      <li><strong>additionalProp1</strong>: object</li>
      <li><strong>additionalProp2</strong>: object</li>
      <li><strong>additionalProp3</strong>: object</li>
    </ul>
  </li>
  <li><strong>error</strong>: string<br>
    Identifier of the error.
  </li>
</ul>

++++

**Responses example**

[source,json]
----
{
  "error": "COMMON",
  "errorId": 0,
  "message": "Sorry for inconvenience. We're fixing the issue. If you have urgent questions, contact support",
  "systemId": "core"
}
----
====

