= *Registration of a new user*

*`POST` v2/mobile/signup*

This endpoint is designed for registering a new user in a mobile application or service using a phone number as the primary identifier.


[IMPORTANT]
====
*When re-registering in the system, it is necessary to use a new phone number that has not been used before.*
====

User registration involves providing necessary information such as the phone number and chosen password.

== *Request*

=== *Headers*

++++
<br><ul>
  <li><strong>X-Merchant-ID:</strong> string (required)<br>
    Identification of requests from users of a specific partner.<br>
    Default: <code>bece038f-2e46-49f4-b25e-89cd38d6dc16</code>
  </li><br>
  <li><strong>X-Version:</strong> string (required)<br>
    Version fingerprint.<br>
    Default: <code><span class="mono">1.2</span></code>
  </li><br>
  <li><strong>X-Fingerprint:</strong> string<br>
    Device fingerprint. Fingerprint for WEB for Android and iOS can be viewed <a href="https://github.com/crypterium-com/api-vault.wiki.git">here</a>.
  </li><br>
  <li><strong>X-Signature:</strong> string<br>
    Contains a digital signature generated both on the server-side (backend) and the client-side (frontend). Used for verifying the authenticity of requests.
  </li>
</ul>
++++


=== *Body*


.Media Type: *application/json*


==== *Parameters*


++++
<br><ul>
<li><strong>phone:</strong> string (Required)<br>
The phone number needed for registration.
</li><br>
<li><strong>password:</strong> string (Required)<br>
The password required for registration. See password creation rule.
</li><br>
<li><strong>analyticsCallback:</strong> string<br>
Optional parameter for transmitting analytics data.
</li>
</ul>
++++



==== **Example body**

[source,json]
----
{
  "phone": "+447871234567",
  "password": "1234Qwerty",
  "analyticsCallback": "string"
}
----

==== **Request Sample: cURL**

At the time of sending the request, the curl command should be as follows:

[source,curl]
----
curl --request POST \
     --url https://api.vault.sandbox.testessential.net/v2/mobile/signup \
     --header 'X-Merchant-ID: bece038f-2e46-49f4-b25e-89cd38d6dc16' \
     --header 'X-Version: 1.2' \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "phone": "+447871234567",
  "password": "1234Qwerty",
  "analyticsCallback": "string"
}
'
----

== Responses

.*`200 - Success Response`*
[%collapsible.200]

====
The response status code indicates that the request was successfully processed.

[.collapsible-content]
.*result*: string
Provides information about the outcome of the registration operation.

**Responses example**
[source,json]
----
{
"result": "ok"
}
----
====

.*`400 - Bad Request`*
[%collapsible.400]
====
The response status code indicates that the requested page was not found on the server.

[.collapsible-content]

.*message:* string
Message displayed to the user.

.*field:* string
Specifies the field in the request that caused the error.

.*errorId:* integer
Identifier of the error.

.*systemId:* string
Identifier of the component.

.*originalMessage:* string
The original error message.

.*errorStackTrace:* string
The place where the error occurred in the code.

.*data:* object
Additional data related to the error, structured as key-value pairs.

** **additionalProp1:** object
** **additionalProp2:** object
** **additionalProp3:** object

.*error:* string
Identifier of the error.

**Responses example**

[source,json]
----
{
  "error": "COMMON",
  "errorId": 0,
  "message": "Sorry for inconvenience. We're fixing the issue. If you have urgent questions, contact support",
  "systemId": "core"
}
----
====


.*`403 - Account Duplication (Phone Number Uniqueness Check)`*
[%collapsible.403]

====
Phone Number Uniqueness Check

Errors related to account duplication and phone number uniqueness check.

If a user attempts to register with a phone number already in the database, they will not receive an error message during the waiting period for SMS confirmation. This is a security measure to prevent unauthorized access to accounts.
====

