= *Get Wallets*

*`GET` /v2/wallets*

[source,http]
----
GET https://api.vault.sandbox.testessential.net/v2/wallets HTTP/1.1
Host: api.vault.sandbox.testessential.net
----

This endpoint provides detailed information about user wallets, including associated accounts and fiat funds. It is designed for retrieving user wallet information.


== Responses


.*`200 - OK`*
[%collapsible.200]
====
The response status code indicates that the request was successfully processed.

[.collapsible-content]
++++
<h4>wallets</h4>
<ul>
  <li><strong>id</strong>: integer<br>
    Wallet identifier in Vault.
  </li>
  <li><strong>name</strong>: string<br>
    Name of the currency being created.
  </li>
  <li><strong>externalId</strong>: string<br>
    External identifier of the wallet in Vault.
  </li>
  <li><strong>address</strong>: string<br>
    Blockchain network address of a specific coin.
  </li>
  <li><strong>currency</strong>: string<br>
    Currency of the wallet.
    Example: BTC, ETH, LTC etc.
  </li>
  <li><strong>baseCurrency</strong>: string<br>
    Base currency of the wallet.
  </li>
  <li><strong>pattern</strong>: string<br>
    Wallet pattern.
  </li>
  <li><strong>balance</strong>: integer<br>
    Current balance of the wallet.
  </li>
  <li><strong>limits</strong>: object<br>
    Wallet limits.
    <ul>
      <li><strong>additionalProp1</strong>: object<br>
        A limit on some operation is imposed on a specific wallet.
        <ul>
          <li><strong>min</strong>: integer<br>
            Minimum limit.
          </li>
          <li><strong>all</strong>: integer<br>
            Overall limit.
          </li>
        </ul>
      </li>
      <li><strong>additionalProp2</strong>: object<br>
        A limit on some operation is imposed on a specific wallet.
        <ul>
          <li><strong>min</strong>: integer<br>
            Minimum limit.
          </li>
          <li><strong>all</strong>: integer<br>
            Overall limit.
          </li>
        </ul>
      </li>
      <li><strong>additionalProp3</strong>: object<br>
        A limit on some operation is imposed on a specific wallet.
        <ul>
          <li><strong>min</strong>: integer<br>
            Minimum limit.
          </li>
          <li><strong>all</strong>: integer<br>
            Overall limit.
          </li>
        </ul>
      </li>
    </ul>
  </li>
  <li><strong>balanceString</strong>: string<br>
    String representation of the balance.
  </li>
  <li><strong>availableBalance</strong>: integer<br>
    Balance that is currently available to the user.
  </li>
  <li><strong>customerId</strong>: integer<br>
    Identifier of the customer associated with the wallet.
  </li>
  <li><strong>createdAt</strong>: string&lt;date-time&gt;<br>
    Wallet creation date.
    Match pattern: YYYY-MM-DDThh:mm:ss&lt;TZDSuffix&gt;
  </li>
  <li><strong>isDebit</strong>: boolean<br>
    Flag indicating whether the wallet is a debit wallet.
    Default: true
  </li>
  <li><strong>allowOperations</strong>: array[string]<br>
    Specifies the allowed operations with the wallet.
  </li>
  <li><strong>color</strong>: string<br>
    Color code associated with the wallet.
  </li>
  <li><strong>fiat</strong>: object<br>
    Fiat wallet representation.
    <ul>
      <li><strong>customerCurrency</strong>: string<br>
        ID, which is stored in the database.
      </li>
      <li><strong>amount</strong>: integer<br>
        A variable that indicates a specific value in rubles.
      </li>
      <li><strong>change</strong>: integer<br>
        A variable that displays changes as a percentage (what happened to the wallet during the day) in fiat currency.
      </li>
      <li><strong>changePercent</strong>: integer<br>
        In percentage.
      </li>
      <li><strong>rate</strong>: integer<br>
        Cryptocurrency to customerCurrency conversion rate.
      </li>
    </ul>
  </li>
  <li><strong>scale</strong>: integer<br>
    A variable that specifies where the comma appears in a number.
  </li>
  <li><strong>stub</strong>: boolean<br>
    Indication of a stub or real wallet.
    Default: true
  </li>
  <li><strong>walletCreationState</strong>: string<br>
    The variable is intended to display the status of the wallet.
    Allowed values:
    <ul>
      <li><strong>Ready</strong>: Status means that a real address has been received and the wallet is ready for use.</li>
      <li><strong>New</strong>: Status means that the wallet has just been created.</li>
      <li><strong>Getting</strong>: Status means that the wallet is in the process of receiving a real address.</li>
    </ul>
  </li>
  <li><strong>iconUrl</strong>: string<br>
    Link to wallet icon.
  </li>
  <li><strong>network</strong>: string<br>
    Token network.
  </li>
  <li><strong>fiat</strong>: object<br>
    Information about user's fiat funds.
    <ul>
      <li><strong>customerCurrency</strong>: string<br>
        ID, which is stored in the database.
      </li>
      <li><strong>amount</strong>: integer<br>
        Amount of fiat funds in customerCurrency.
      </li>
      <li><strong>change</strong>: integer<br>
        A variable that displays changes as a percentage (what happened to the wallet during the day).
      </li>
      <li><strong>changePercent</strong>: integer<br>
        Change percentage in fiat currency.
      </li>
      <li><strong>rate</strong>: integer<br>
        Exchange rate.
      </li>
    </ul>
  </li>
</ul>

++++

**Responses example**
[source,json]
----
{
  "wallets": [
    {
      "id": -1,
      "fiat": {
        "rate": 0.12068,
        "amount": 0,
        "change": 0,
        "changePercent": -1.14,
        "customerCurrency": "EUR"
      },
      "name": "TRX",
      "stub": true,
      "color": "#EB322A",
      "debit": true,
      "scale": 5,
      "limits": {
        "PAYOUT_CRYPTO": {
          "all": 0,
          "min": 0.00001
        }
      },
      "address": "",
      "balance": 0,
      "currency": "TRX",
      "customerId": 5787,
      "balanceString": "0",
      "allowOperations": [],
      "availableBalance": 0,
      "walletCreationState": "READY"
    },
    {
      "id": 5822,
      "fiat": {
        "rate": 0.63421,
        "amount": 0,
        "change": 0,
        "changePercent": 10.87,
        "customerCurrency": "EUR"
      },
      "name": "XRP",
      "stub": false,
      "color": "#262A3C",
      "debit": true,
      "scale": 6,
      "limits": {
        "PAYOUT_CRYPTO": {
          "all": 0,
          "min": 20
        }
      },
      "address": "rnrve1cZDyLv225wv9Xre1nD5EWRjS4CW2?dt=27",
      "balance": 0,
      "pattern": "^r[0-9a-zA-Z]{24,34}(\\?dt=\\d+)?$",
      "currency": "XRP",
      "customerId": 5787,
      "balanceString": "0",
      "allowOperations": [
        "TRANSFER_MOBILE",
        "PAYIN_CRYPTO",
        "WALLETTO_CARD_PAYLOAD",
        "WALLETTO_CARD",
        "COMMON",
        "WALLET_SCREEN",
        "PAYOUT_CRYPTO",
        "EXCHANGE",
        "PAYIN_CARD",
        "PAYOUT_CARD",
        "WALLETTO_PAY_FOR_CARD",
        "Common"
      ],
      "availableBalance": 0,
      "walletCreationState": "READY"
    },
    {
      "id": 5792,
      "fiat": {
        "rate": 65628.5,
        "amount": 130540.48,
        "change": 659.74,
        "changePercent": 0.51,
        "customerCurrency": "EUR"
      },
      "name": "BTC",
      "stub": false,
      "color": "#FF8724",
      "debit": true,
      "scale": 8,
      "limits": {
        "PAYOUT_CRYPTO": {
          "all": 1.98655697,
          "min": 0.001
        }
      },
      "address": "2NFnhQrRUbQT57YSx9oZRwWZrTXu8PVFQzq",
      "balance": 1.98908205,
      "pattern": "^(bitcoin:|btc:)?([123][a-km-zA-HJ-NP-Z1-9]{25,34}$)|(bc1[\\w]{25,}$)",
      "currency": "BTC",
      "customerId": 5787,
      "balanceString": "1.98908205",
      "allowOperations": [
        "TRANSFER_MOBILE",
        "PAYIN_CRYPTO",
        "WALLETTO_CARD_PAYLOAD",
        "WALLETTO_CARD",
        "COMMON",
        "WALLET_SCREEN",
        "PAYOUT_CRYPTO",
        "EXCHANGE",
        "PAYIN_CARD",
        "PAYOUT_CARD",
        "WALLETTO_PAY_FOR_CARD",
        "Common"
      ],
      "availableBalance": 1.98908205,
      "walletCreationState": "READY"
    },
    {
      "id": 5794,
      "fiat": {
        "rate": 89.09,
        "amount": 356.28,
        "change": 17.48,
        "changePercent": 4.91,
        "customerCurrency": "EUR"
      },
      "name": "LTC",
      "stub": false,
      "color": "#9B9AA9",
      "debit": true,
      "scale": 8,
      "limits": {
        "PAYOUT_CRYPTO": {
          "all": 3.993721,
          "min": 0.01
        }
      },
      "address": "QbRntihVRPxio1epdKaHpG2d1y8zKokkVm",
      "balance": 3.999,
      "pattern": "^(litecoin:)?([LM3Q2][a-km-zA-HJ-NP-Z1-9]{26,33})|(ltc1[\\w]{25,})$",
      "currency": "LTC",
      "customerId": 5787,
      "balanceString": "3.999",
      "allowOperations": [
        "TRANSFER_MOBILE",
        "PAYIN_CRYPTO",
        "WALLETTO_CARD_PAYLOAD",
        "WALLETTO_CARD",
        "COMMON",
        "WALLET_SCREEN",
        "PAYOUT_CRYPTO",
        "EXCHANGE",
        "PAYIN_CARD",
        "PAYOUT_CARD",
        "WALLETTO_PAY_FOR_CARD",
        "Common"
      ],
      "availableBalance": 3.999,
      "walletCreationState": "READY"
    }
  ]
}
----
====

.*`400 - Bad Request`*
[%collapsible.400]
====
The response status code indicates that the requested page was not found on the server.

++++
<h4>Body</h4>
<ul>
  <li><strong>message</strong>: string<br>
    Message displayed to the user.
  </li>
  <li><strong>field</strong>: string<br>
    Specifies the field in the request that caused the error.
  </li>
  <li><strong>errorId</strong>: integer<br>
    Identifier of the error.
  </li>
  <li><strong>systemId</strong>: string<br>
    Identifier of the component.
  </li>
  <li><strong>originalMessage</strong>: string<br>
    The original error message.
  </li>
  <li><strong>errorStackTrace</strong>: string<br>
    The place where the error occurred in the code.
  </li>
  <li><strong>data</strong>: object<br>
    Additional data related to the error, structured as key-value pairs.
    <ul>
      <li><strong>additionalProp1</strong>: object</li>
      <li><strong>additionalProp2</strong>: object</li>
      <li><strong>additionalProp3</strong>: object</li>
    </ul>
  </li>
  <li><strong>error</strong>: string<br>
    Identifier of the error.
  </li>
</ul>
++++

**Responses example**

[source,json]
----
{
  "error": "COMMON",
  "errorId": 0,
  "message": "Sorry for inconvenience. We're fixing the issue. If you have urgent questions, contact support",
  "systemId": "core"
}
----

====