= *Get Wallets*

*`GET` /v2/wallets*

[source,http]
----
GET https://api.vault.sandbox.testessential.net/v2/wallets HTTP/1.1
Host: api.vault.sandbox.testessential.net
----

This endpoint provides detailed information about user wallets, including associated accounts and fiat funds. It is designed for retrieving user wallet information.


== Responses

[.collapsible]
====
*`201 - Created`*

The response status code indicates that the request was successfully processed.

[.collapsible-content]


.*wallets*
array[object]
list of created wallets with detailed information for each.

* *id*: integer
wallet identifier in Vault.

* *name*: string
name of the currency being created.

* *externalId*: string
external identifier of the wallet in Vault.

* *address*: string
blockchain network address of a specific coin.

* *currency*: string
currency of the wallet.
Example: BTC, ETH, LTC etc.

* *baseCurrency*: string
base currency of the wallet.

* *pattern*: string
wallet pattern.

* *balance*: integer
current balance of the wallet.

* *limits*: object
wallet limits.

** **additionalProp1**: object
a limit on some operation is imposed on a specific wallet.

** **additionalProp2**: object
a limit on some operation is imposed on a specific wallet.

** **additionalProp3**: object
a limit on some operation is imposed on a specific wallet.

* *balanceString*: string
string representation of the balance.

* *availableBalance*: integer
balance that is currently available to the user.

* *customerId*: integer
identifier of the customer associated with the wallet.

* *createdAt*: string<date-time>
date and time of wallet creation.
Match pattern: YYYY-MM-DDThh:mm:ss<TZDSuffix>

* *isDebit*: boolean
flag indicating whether the wallet is a debit wallet.
Default: true

* *allowOperations*: array[string]
specifies the allowed operations with the wallet.

* *color*: string
color code associated with the wallet.

* *fiat*: object
information about the wallet in fiat currency.

** **customerCurrency**: string
customer's currency.

** **amount**: integer
a variable that indicates a specific value in rubles.

** **change**: integer
a variable that displays changes as a percentage (what happened to the wallet during the day) in fiat currency.

** **changePercent**: integer
in percentage.

** **rate**: integer
cryptocurrency to customerCurrency conversion rate.


* *scale*: integer
a variable that specifies where the comma appears in a number.

* *stub*: boolean
indication of a stub or real wallet.
Default: true

* *walletCreationState*: string
the variable is intended to display the status of the wallet.
Allowed values:
- *Ready*: Status means that a real address has been received and the wallet is ready for use.
- *New*: Status means that the wallet has just been created.
- *Getting*: Status means that the wallet is in the process of receiving a real address.

* *iconUrl*: string
link to wallet icon.

* *network*: string
wallet network.

.*fiat*: object
information about user fiat funds.

* *customerCurrency*: string
id, which is stored in the database.

* *amount*: integer
a variable that indicates a specific value in customerCurrency.

* *change*: integer
a variable that displays changes as a percentage (what happened to the wallet during the day).

* *changePercent*: integer
change percentage in fiat currency.

* *rate*: integer
exchange rate.


**Responses example**
[source,json]
----
{
  "wallets": [
    {
      "id": -1,
      "fiat": {
        "rate": 0.12068,
        "amount": 0,
        "change": 0,
        "changePercent": -1.14,
        "customerCurrency": "EUR"
      },
      "name": "TRX",
      "stub": true,
      "color": "#EB322A",
      "debit": true,
      "scale": 5,
      "limits": {
        "PAYOUT_CRYPTO": {
          "all": 0,
          "min": 0.00001
        }
      },
      "address": "",
      "balance": 0,
      "currency": "TRX",
      "customerId": 5787,
      "balanceString": "0",
      "allowOperations": [],
      "availableBalance": 0,
      "walletCreationState": "READY"
    },
    {
      "id": 5822,
      "fiat": {
        "rate": 0.63421,
        "amount": 0,
        "change": 0,
        "changePercent": 10.87,
        "customerCurrency": "EUR"
      },
      "name": "XRP",
      "stub": false,
      "color": "#262A3C",
      "debit": true,
      "scale": 6,
      "limits": {
        "PAYOUT_CRYPTO": {
          "all": 0,
          "min": 20
        }
      },
      "address": "rnrve1cZDyLv225wv9Xre1nD5EWRjS4CW2?dt=27",
      "balance": 0,
      "pattern": "^r[0-9a-zA-Z]{24,34}(\\?dt=\\d+)?$",
      "currency": "XRP",
      "customerId": 5787,
      "balanceString": "0",
      "allowOperations": [
        "TRANSFER_MOBILE",
        "PAYIN_CRYPTO",
        "WALLETTO_CARD_PAYLOAD",
        "WALLETTO_CARD",
        "COMMON",
        "WALLET_SCREEN",
        "PAYOUT_CRYPTO",
        "EXCHANGE",
        "PAYIN_CARD",
        "PAYOUT_CARD",
        "WALLETTO_PAY_FOR_CARD",
        "Common"
      ],
      "availableBalance": 0,
      "walletCreationState": "READY"
    },
    {
      "id": 5792,
      "fiat": {
        "rate": 65628.5,
        "amount": 130540.48,
        "change": 659.74,
        "changePercent": 0.51,
        "customerCurrency": "EUR"
      },
      "name": "BTC",
      "stub": false,
      "color": "#FF8724",
      "debit": true,
      "scale": 8,
      "limits": {
        "PAYOUT_CRYPTO": {
          "all": 1.98655697,
          "min": 0.001
        }
      },
      "address": "2NFnhQrRUbQT57YSx9oZRwWZrTXu8PVFQzq",
      "balance": 1.98908205,
      "pattern": "^(bitcoin:|btc:)?([123][a-km-zA-HJ-NP-Z1-9]{25,34}$)|(bc1[\\w]{25,}$)",
      "currency": "BTC",
      "customerId": 5787,
      "balanceString": "1.98908205",
      "allowOperations": [
        "TRANSFER_MOBILE",
        "PAYIN_CRYPTO",
        "WALLETTO_CARD_PAYLOAD",
        "WALLETTO_CARD",
        "COMMON",
        "WALLET_SCREEN",
        "PAYOUT_CRYPTO",
        "EXCHANGE",
        "PAYIN_CARD",
        "PAYOUT_CARD",
        "WALLETTO_PAY_FOR_CARD",
        "Common"
      ],
      "availableBalance": 1.98908205,
      "walletCreationState": "READY"
    },
    {
      "id": 5794,
      "fiat": {
        "rate": 89.09,
        "amount": 356.28,
        "change": 17.48,
        "changePercent": 4.91,
        "customerCurrency": "EUR"
      },
      "name": "LTC",
      "stub": false,
      "color": "#9B9AA9",
      "debit": true,
      "scale": 8,
      "limits": {
        "PAYOUT_CRYPTO": {
          "all": 3.993721,
          "min": 0.01
        }
      },
      "address": "QbRntihVRPxio1epdKaHpG2d1y8zKokkVm",
      "balance": 3.999,
      "pattern": "^(litecoin:)?([LM3Q2][a-km-zA-HJ-NP-Z1-9]{26,33})|(ltc1[\\w]{25,})$",
      "currency": "LTC",
      "customerId": 5787,
      "balanceString": "3.999",
      "allowOperations": [
        "TRANSFER_MOBILE",
        "PAYIN_CRYPTO",
        "WALLETTO_CARD_PAYLOAD",
        "WALLETTO_CARD",
        "COMMON",
        "WALLET_SCREEN",
        "PAYOUT_CRYPTO",
        "EXCHANGE",
        "PAYIN_CARD",
        "PAYOUT_CARD",
        "WALLETTO_PAY_FOR_CARD",
        "Common"
      ],
      "availableBalance": 3.999,
      "walletCreationState": "READY"
    }
  ]
}
----

====

[.collapsible]
====
*`400 - Bad Request`*

The response status code indicates that the requested page was not found on the server.

[.collapsible-content]

.*message:* string
Message displayed to the user.

.*field:* string
Specifies the field in the request that caused the error.

.*errorId:* integer
Identifier of the error.

.*systemId:* string
Identifier of the component.

.*originalMessage:* string
The original error message.

.*errorStackTrace:* string
The place where the error occurred in the code.

.*data:* object
Additional data related to the error, structured as key-value pairs.

** **additionalProp1:** object
** **additionalProp2:** object
** **additionalProp3:** object

.*error:* string
Identifier of the error.

**Responses example**

[source,json]
----
{
  "error": "COMMON",
  "errorId": 0,
  "message": "Sorry for inconvenience. We're fixing the issue. If you have urgent questions, contact support",
  "systemId": "core"
}
----

====

