= *SignIn*

*`POST` /oauth/token*

The endpoint is designed for user authentication and obtaining an OAuth access token. Specifically tailored for the client credentials grant type, it generates a token upon successful authentication, enabling secure requests to resources.


== *Request*

=== *Headers*

- *X-Merchant-ID*: string (required)
Identification of requests from users of a specific partner.
Default: `bece038f-2e46-49f4-b25e-89cd38d6dc16`

=== *Body*


.Media Type: *application/x-www-form-urlencoded*


==== *Parameters*


- *password*: string
Password that must be specified during registration.

- *number*: string
Phone number that is transmitted when receiving a token.

- *grant_type*: string (Required)
Authorization type: `mobile_phone`.


==== **Example body**

[source,json]
----
{
  "password": "1234Qwerty",
  "number": "+447871239999",
  "grant_type": "mobile_phone"
}
----

==== **Request Sample: cURL**

At the time of sending the request, the curl command should be as follows:

[source,curl]
----
curl --request POST \
  --url https://api.vault.sandbox.testessential.net/oauth/token \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --header 'X-Merchant-ID: bece038f-2e46-49f4-b25e-89cd38d6dc16' \
  --data 'password=+447871239999' \
  --data number=1234Qwerty \
  --data grant_type=mobile_phone
----

== Responses

[.collapsible]
====
*`200 - Success Response`*

The response status code indicates that the request was successfully processed.

[.collapsible-content]

Indicates that the request was successfully processed.

.**access_token**: string
An encrypted key, a short-lived token for accessing a resource.

.**token_type**: string
A string representing the token type, typically `Bearer`.

.**refresh_token**: string
These are credentials for accessing the API in the absence of a user session.

.**expires_in**: integer
Token expiration time in seconds.

.**scope**: string
A string representing the token's access scope, e.g., `read write`.

.**jti**: string
Unique token identifier.

[source,json]
----
{
  "jti": "nejUZ1PeSBnmTtrZdaAj81sQX44",
  "scope": "read write",
  "expires_in": 86399,
  "token_type": "bearer",
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNTFhYTc3Mi0yNDk4LTQ0ZTEtODdmYi0zYzNhZDdlMTY1ODgiLCJleHAiOjE3MDk4MDQzNjksImlhdCI6MTcwOTcxNzk2OX0.9nA1ur5_fGwlap2mrPN35OhR6dJ0M5qmNLNjJ2iZM6g",
  "refresh_token": "qPMkKwoedBu2lVZzn9-51hkG_vg"
}
----


====

[.collapsible]
====
*`400 - Bad Request`*

The response status code indicates that the requested page was not found on the server.

[.collapsible-content]

.*message:* string
Message displayed to the user.

.*field:* string
Specifies the field in the request that caused the error.

.*errorId:* integer
Identifier of the error.

.*systemId:* string
Identifier of the component.

.*originalMessage:* string
The original error message.

.*errorStackTrace:* string
The place where the error occurred in the code.

.*data:* object
Additional data related to the error, structured as key-value pairs.

** **additionalProp1:** object
** **additionalProp2:** object
** **additionalProp3:** object

.*error:* string
Identifier of the error.

**Responses example**

[source,json]
----
{
  "error": "COMMON",
  "errorId": 0,
  "message": "Sorry for inconvenience. We're fixing the issue. If you have urgent questions, contact support",
  "systemId": "core"
}
----

====
