= *Start*

*`POST` /v4/kyc/start*

The endpoint is crafted to commence the KYC1 V4 (Know Your Customer Level 1, version 4) identification process, serving as the first step in customer verification and supplying an identifier for continuous monitoring of KYC1 V4 status or acquiring supplementary details.

The process of completing KYC 1 can be read link:https://api-vault.readme.io/docs/kyc-procedure[here].


== *Request*

=== *Query Parameters*

++++
<br><ul>
  <li><strong>platform:</strong> string<br>
    Types of platforms.<br>
    <ul>
      <li><strong>Default:</strong> COMMON</li>
    </ul>
  </li>
</ul>
++++

Allowed values for the field:

* *COMMON*: Represents the common value.
* *WALLETTO*: Represents the Walletto value.

== Responses

.*`200 - OK`*
[%collapsible.200]

====
The response status code indicates that the request was successfully processed.

++++
<br><ul>
  <li><strong>id:</strong> string<br>
    A unique identifier that can be used for further interaction with the KYC1 V4 process.
  </li>
</ul>

++++

**Responses example**
[source,json]
----
{
  "id": "118feeff71324519728"
}
----
====

.*`400 - Bad Request`*
[%collapsible.400]
====
The response status code indicates that the requested page was not found on the server.

++++
<h4>Body</h4>
<ul>
  <li><strong>message</strong>: string<br>
    Message displayed to the user.
  </li>
  <li><strong>field</strong>: string<br>
    Specifies the field in the request that caused the error.
  </li>
  <li><strong>errorId</strong>: integer<br>
    Identifier of the error.
  </li>
  <li><strong>systemId</strong>: string<br>
    Identifier of the component.
  </li>
  <li><strong>originalMessage</strong>: string<br>
    The original error message.
  </li>
  <li><strong>errorStackTrace</strong>: string<br>
    The place where the error occurred in the code.
  </li>
  <li><strong>data</strong>: object<br>
    Additional data related to the error, structured as key-value pairs.
    <ul>
      <li><strong>additionalProp1</strong>: object</li>
      <li><strong>additionalProp2</strong>: object</li>
      <li><strong>additionalProp3</strong>: object</li>
    </ul>
  </li>
  <li><strong>error</strong>: string<br>
    Identifier of the error.
  </li>
</ul>

++++
**Responses example**

[source,json]
----
{
  "error": "COMMON",
  "errorId": 0,
  "message": "Sorry for inconvenience. We're fixing the issue. If you have urgent questions, contact support",
  "systemId": "core"
}
----
====


