= *Update Status of Push Notifications*

*`PUT` /v1/customer/device/push*

This endpoint is used to enable or disable push notifications on a specific device. It is generated by the user when toggling the push notification settings within the application. Additionally, it is used after receiving permission for push notifications in iOS (system popup).

== *Request*

=== *Headers*

++++
<br><ul>
  <li><strong>User-Agent:</strong> string <span style="color:red">(required)</span><br>
    User identifier making the request.<br>
    Default: <code>vault/4.0(508) dart/3.2 (dart:io) ios/17.3.1; iphone 9da12fa6-716c-4cdc-a24c</code>
  </li><br>
  <li><strong>X-Version:</strong> string <span style="color:red">(required)</span><br>
    Version fingerprint.<br>
    Default: <code>1.2</code>
  </li><br>
</ul>

++++

=== *Body*


.Media Type: *application/json*


==== *Parameters*

++++
<br><ul>
  <li><strong>state:</strong> string<br>
    Indicates the desired state of push notifications.
  </li><br>
  <li><strong>deviceToken:</strong> string<br>
    A unique identifier for the device.
  </li><br>
  <li><strong>deviceId:</strong> string<br>
    Identifier for the specific device.
  </li><br>
</ul>

++++




==== **Example body**

[source,json]
----
{
  "state": "ENABLED",
  "deviceToken": "abc123xyz456",
  "deviceId": "device123"
}
----

==== **Request Sample: cURL**

At the time of sending the request, the curl command should be as follows:

[source,curl]
----
curl --request PUT \
     --url https://api.vault.sandbox.testessential.net/v1/customer/device/push \
     --header 'User-Agent: vault/4.0(508) dart/3.2 (dart:io) ios/17.3.1' \
     --header 'X-Version: 1.2' \
     --header 'accept: application/json' \
     --header 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NTU0ZDc0My05ZDExLTQ5YTEtYTMyMy03YmRmOGQ4NDdjMjEiLCJleHAiOjE3MDk3MjQ1NjQsImlhdCI6MTcwOTYzODE2NH0.deZXGfjS7oVprz2XoZseeYa7l8ti8aAJaELBeDDtglI' \
     --header 'content-type: application/json' \
     --data '
{
  "state": "ENABLED",
  "deviceToken": "abc123xyz456",
  "deviceId": "device123"
}
'
----

== Responses

.*`200 - Success Response`*
[%collapsible.200]

====
The response status code indicates that the request was successfully processed.

[.collapsible-content]
.*result*: string
A string indicating the result of the operation.

**Responses example**
[source,json]
----
{
"result": "ok"
}
----
====


.*`400 - Bad Request`*
[%collapsible.400]
====
The response status code indicates that the requested page was not found on the server.

++++
<h4>Body</h4>
<ul>
  <li><strong>message</strong>: string<br>
    Message displayed to the user.
  </li>
  <li><strong>field</strong>: string<br>
    Specifies the field in the request that caused the error.
  </li>
  <li><strong>errorId</strong>: integer<br>
    Identifier of the error.
  </li>
  <li><strong>systemId</strong>: string<br>
    Identifier of the component.
  </li>
  <li><strong>originalMessage</strong>: string<br>
    The original error message.
  </li>
  <li><strong>errorStackTrace</strong>: string<br>
    The place where the error occurred in the code.
  </li>
  <li><strong>data</strong>: object<br>
    Additional data related to the error, structured as key-value pairs.
    <ul>
      <li><strong>additionalProp1</strong>: object</li>
      <li><strong>additionalProp2</strong>: object</li>
      <li><strong>additionalProp3</strong>: object</li>
    </ul>
  </li>
  <li><strong>error</strong>: string<br>
    Identifier of the error.
  </li>
</ul>

++++

**Responses example**

[source,json]
----
{
  "error": "COMMON",
  "errorId": 0,
  "message": "Sorry for inconvenience. We're fixing the issue. If you have urgent questions, contact support",
  "systemId": "core"
}
----
====



